# Application properties
server.port=1406
spring.application.name=UnifiedWorkflowApplication

# TemporalConstants properties
spring.temporal.namespace=default
spring.temporal.connection.target=localhost:7233

# Workflow Orchestration
spring.temporal.workers[0].task-queue=workflow-orchestration-queue
spring.temporal.workers[0].workflowClasses[0]=com.innodata.platform.automation.orchestrator.workflow.WorkflowOrchestratorImpl
spring.temporal.workers[0].activityBeans[0]=contentActivitiesImpl
spring.temporal.workers[0].activityBeans[1]=emailActivitiesImpl
spring.temporal.workers[0].activityBeans[2]=ticketActivitiesImpl

# Email Service
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${email-address}
spring.mail.password=${email-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000